const fs   = require("fs");
const path = require("path");
const { select } = require("@inquirer/prompts");
const logger = require("../utilities/logger.cjs");

const ROOT = path.resolve(__dirname, "../../");

const ENVS = {
  dev:  { src: ".env.dev",  label: "Development", apiBase: "http://localhost:5001/doona-hiring/us-central1" },
  stg:  { src: ".env.stg",  label: "Staging",     apiBase: "https://stg-proxy.doona.com" },
  prod: { src: ".env.prod", label: "Production",  apiBase: "https://proxy.doona.com" },
};

const TARGET     = path.resolve(ROOT, ".env");
const CONFIG_DIR = path.resolve(ROOT, "src/configs");
const CONFIG_OUT = path.resolve(CONFIG_DIR, "env.js");

/**
 * Prompts the user to select an environment, copies its .env.[env] file into .env,
 * and auto-generates src/configs/env.js with typed runtime constants.
 *
 * @returns {Promise<void>}
 */
async function run() {
  const env = await select({
    message: "Select environment:",
    choices: Object.entries(ENVS).map(([value, { label }]) => ({ name: label, value })),
  });

  const cfg    = ENVS[env];
  const source = path.resolve(ROOT, cfg.src);

  if (!fs.existsSync(source)) {
    logger.error(`Source file not found: ${cfg.src}`);
    logger.error(`Create it by copying .env.example → ${cfg.src}`);
    process.exit(1);
  }

  // 1. Copy the correct .env file
  fs.copyFileSync(source, TARGET);

  // 2. Generate src/configs/env.js
  fs.mkdirSync(CONFIG_DIR, { recursive: true });

  const configContent = [
    `// AUTO-GENERATED by scripts/logic/setEnv.cjs — do not edit manually`,
    `// Environment : ${cfg.label}`,
    `// Generated  : ${new Date().toISOString()}`,
    ``,
    `export const ENV        = /** @type {'dev'|'stg'|'prod'} */ ('${env}');`,
    `export const IS_DEV     = ${env === "dev"};`,
    `export const IS_STG     = ${env === "stg"};`,
    `export const IS_PROD    = ${env === "prod"};`,
    `export const API_BASE   = '${cfg.apiBase}';`,
    `export const BUILD_TIME = '${new Date().toISOString()}';`,
    ``,
  ].join("\n");

  fs.writeFileSync(CONFIG_OUT, configContent, "utf8");

  logger.box(`.env + src/configs/env.js  →  [ ${env.toUpperCase()} ]`);
}

run();
